const SET_NAV_INDEX = 'SET_NAV_INDEX';
const SET_ANIMATION_NAME = 'SET_ANIMATION_NAME';
const SET_CACHE_LIST = 'SET_CACHE_LIST';
const SET_TO_PATH = 'SET_TO_PATH';

export default{
	SET_NAV_INDEX,
	SET_ANIMATION_NAME,
	SET_CACHE_LIST,
	SET_TO_PATH
}
